"""empty message

Revision ID: 2bb611464310
Revises: 64e8ccc4389f
Create Date: 2022-05-03 18:25:58.160470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2bb611464310'
down_revision = '64e8ccc4389f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('charachters', 'home_planet',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('charachters', 'persons_age',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('charachters', 'persons_species',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.drop_index('charachter_name', table_name='charachters')
    op.drop_index('charachter_name_2', table_name='charachters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('charachter_name_2', 'charachters', ['charachter_name'], unique=False)
    op.create_index('charachter_name', 'charachters', ['charachter_name'], unique=False)
    op.alter_column('charachters', 'persons_species',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('charachters', 'persons_age',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('charachters', 'home_planet',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
